from_mapping:
  "UK": "Unknown"
  "BAH": "Bahrain"
  "LGW": "London Gatwick"
  "PUJ": "Punta Cana"
  "SVG": "Stavanger"
  "ORY": "Paris Orly"
  "GOT": "Gothenburg Landvetter"
  "IKA": "Tehran"
  "LBA": "Leeds Bradford"
  "TPA": "Tampa"
  "LAX": "Los Angeles"
  "SOF": "Sofia"
  "IAD": "Washington Dulles"
  "YVR": "Vancouver"
  "MAD": "Madrid"
  "MLA": "Malta"
  "SFO": "San Francisco"
  "CDG": "Paris Charles de Gaulle"
  "BKK": "Bangkok"
  "GLA": "Glasgow"
  "LED": "Saint Petersburg"
  "PVG": "Shanghai Pudong"
  "JFK": "New York JFK"
  "ATH": "Athens"
  "FUE": "Fuerteventura"
  "IAH": "Houston"
  "KUL": "Kuala Lumpur"
  "MAN": "Manchester"
  "MIA": "Miami"
  "SYD": "Sydney"
  "YYZ": "Toronto Pearson"
  "ARN": "Stockholm Arlanda"
  "CUN": "Cancún"
  "DXB": "Dubai"
  "BUD": "Budapest"
  "FRA": "Frankfurt"
  "BWI": "Baltimore/Washington"
  "KBP": "Kyiv Boryspil"
  "UVF": "Saint Lucia"
  "SAN": "San Diego"
  "DFW": "Dallas/Fort Worth"
  "CTU": "Chengdu"
  "NBO": "Nairobi"
  "SEA": "Seattle-Tacoma"
  "SIN": "Singapore Changi"
  "MAA": "Chennai"
  "TLV": "Tel Aviv Ben Gurion"
  "RAK": "Marrakesh Menara"
  "AMS": "Amsterdam Schiphol"
  "DUS": "Düsseldorf"
  "JNB": "Johannesburg"
  "CPT": "Cape Town"
  "BCN": "Barcelona El Prat"
  "LIS": "Lisbon"
  "DUB": "Dublin"
  "MRU": "Mauritius"
  "LCA": "Larnaca"
  "ICN": "Seoul Incheon"
  "KWI": "Kuwait"
  "EDI": "Edinburgh"
  "CNX": "Chiang Mai"
  "HND": "Tokyo Haneda"
  "BRI": "Bari"
  "PMI": "Palma de Mallorca"
  "AGP": "Málaga"
  "DBV": "Dubrovnik"
  "YYC": "Calgary"
  "LCY": "London City"
  "LAS": "Las Vegas McCarran"
  "BOS": "Boston Logan"
  "SJO": "San José Juan Santamaría"
  "MEL": "Melbourne"
  "SJC": "San Jose Mineta"
  "ATL": "Atlanta Hartsfield-Jackson"
  "AUH": "Abu Dhabi"
  "NAP": "Naples"
  "OPO": "Porto"
  "MUC": "Munich"
  "VIE": "Vienna"
  "PRG": "Prague Václav Havel"
  "PHX": "Phoenix Sky Harbor"
  "TXL": "Berlin Tegel"
  "WAW": "Warsaw Chopin"
  "PHL": "Philadelphia"
  "ABV": "Abuja Nnamdi Azikiwe"
  "ZRH": "Zurich"
  "MEX": "Mexico City"
  "DOH": "Doha Hamad"
  "GRU": "São Paulo Guarulhos"
  "BLR": "Bangalore Kempegowda"
  "ABZ": "Aberdeen"
  "BSL": "Basel EuroAirport"
  "MXP": "Milan Malpensa"
  "GVA": "Geneva"
  "MRS": "Marseille Provence"
  "NCL": "Newcastle"
  "NAS": "Nassau Lynden Pindling"
  "BGI": "Bridgetown Grantley Adams"
  "IBZ": "Ibiza"
  "LYS": "Lyon Saint-Exupéry"
  "PSA": "Pisa Galileo Galilei"
  "ACC": "Accra Kotoka"
  "OSL": "Oslo Gardermoen"
  "ORD": "Chicago O'Hare"
  "FCO": "Rome Fiumicino"
  "GIB": "Gibraltar"
  "PEK": "Beijing Capital"
  "RUH": "Riyadh King Khalid"
  "CPH": "Copenhagen"
  "SVQ": "Seville"
  "IST": "Istanbul"
  "TRN": "Turin"
  "AUS": "Austin-Bergstrom"
  "HEL": "Helsinki-Vantaa"
  "VCE": "Venice Marco Polo"
  "LHR - EDI": "London Heathrow to Edinburgh"
  "OUL": "Oulu"
  "OTP": "Bucharest Henri Coandă"
  "MCO": "Orlando"
  "FNC": "Portugal"
  "iAH": "Houston"
  "NCE": "France"
  "YVR-LIS via LHR": "Richmond, Canada"
  "JED": "Jeddah"
  "YUL": "Dorval, Canada"
  "Hannover": "Germany"
  "Kiev": "Ukraine"
  "SSH": "Sharm el-Sheikh, Egypt"
  "Heathrow (London)": "London"
  "Fuereventura": "Spain"
  "lgw": "London"
  "St Kitts": "Saint Kitts and Nevis"
  "DME": "Moscow"
  "Lebanon": "Lebanon"
  "MAN-LHR": "Manchester"
  "Istambul": "Istambul"
  "Verona": "Verona"
  "LHR-BOM": "London"
  "Vancouver Canada": "Vancouver"
  "CAI": "Egypt"
  "Helsinki": "Helsinki"
  "LHR-DEN": "London"
  "ORD-LHR": "Chicago"
  "LHR-GLA": "London"
  "GLA-LHR": "London"

to_mapping:
  "BAH": "Bahrain"
  "LGW": "London Gatwick"
  "PUJ": "Punta Cana"
  "SVG": "Stavanger"
  "ORY": "Paris Orly"
  "GOT": "Gothenburg Landvetter"
  "IKA": "Tehran"
  "LBA": "Leeds Bradford"
  "TPA": "Tampa"
  "LAX": "Los Angeles"
  "SOF": "Sofia"
  "IAD": "Washington Dulles"
  "YVR": "Vancouver"
  "MAD": "Madrid"
  "MLA": "Malta"
  "SFO": "San Francisco"
  "CDG": "Paris Charles de Gaulle"
  "BKK": "Bangkok"
  "GLA": "Glasgow"
  "LED": "Saint Petersburg"
  "PVG": "Shanghai Pudong"
  "JFK": "New York JFK"
  "ATH": "Athens"
  "FUE": "Fuerteventura"
  "IAH": "Houston"
  "KUL": "Kuala Lumpur"
  "MAN": "Manchester"
  "MIA": "Miami"
  "SYD": "Sydney"
  "YYZ": "Toronto Pearson"
  "ARN": "Stockholm Arlanda"
  "CUN": "Cancún"
  "DXB": "Dubai"
  "BUD": "Budapest"
  "FRA": "Frankfurt"
  "BWI": "Baltimore/Washington"
  "KBP": "Kyiv Boryspil"
  "UVF": "Saint Lucia"
  "SAN": "San Diego"
  "DFW": "Dallas/Fort Worth"
  "CTU": "Chengdu"
  "NBO": "Nairobi"
  "SEA": "Seattle-Tacoma"
  "SIN": "Singapore Changi"
  "MAA": "Chennai"
  "TLV": "Tel Aviv Ben Gurion"
  "RAK": "Marrakesh Menara"
  "AMS": "Amsterdam Schiphol"
  "DUS": "Düsseldorf"
  "JNB": "Johannesburg"
  "CPT": "Cape Town"
  "BCN": "Barcelona El Prat"
  "LIS": "Lisbon"
  "DUB": "Dublin"
  "MRU": "Mauritius"
  "LCA": "Larnaca"
  "ICN": "Seoul Incheon"
  "KWI": "Kuwait"
  "EDI": "Edinburgh"
  "CNX": "Chiang Mai"
  "HND": "Tokyo Haneda"
  "BRI": "Bari"
  "PMI": "Palma de Mallorca"
  "AGP": "Málaga"
  "DBV": "Dubrovnik"
  "YYC": "Calgary"
  "LCY": "London City"
  "LAS": "Las Vegas McCarran"
  "BOS": "Boston Logan"
  "SJO": "San José Juan Santamaría"
  "MEL": "Melbourne"
  "SJC": "San Jose Mineta"
  "ATL": "Atlanta Hartsfield-Jackson"
  "AUH": "Abu Dhabi"
  "NAP": "Naples"
  "OPO": "Porto"
  "MUC": "Munich"
  "VIE": "Vienna"
  "PRG": "Prague Václav Havel"
  "PHX": "Phoenix Sky Harbor"
  "TXL": "Berlin Tegel"
  "WAW": "Warsaw Chopin"
  "PHL": "Philadelphia"
  "ABV": "Abuja Nnamdi Azikiwe"
  "ZRH": "Zurich"
  "MEX": "Mexico City"
  "DOH": "Doha Hamad"
  "GRU": "São Paulo Guarulhos"
  "BLR": "Bangalore Kempegowda"
  "ABZ": "Aberdeen"
  "BSL": "Basel EuroAirport"
  "MXP": "Milan Malpensa"
  "GVA": "Geneva"
  "MRS": "Marseille Provence"
  "NCL": "Newcastle"
  "NAS": "Nassau Lynden Pindling"
  "BGI": "Bridgetown Grantley Adams"
  "IBZ": "Ibiza"
  "LYS": "Lyon Saint-Exupéry"
  "PSA": "Pisa Galileo Galilei"
  "ACC": "Accra Kotoka"
  "OSL": "Oslo Gardermoen"
  "ORD": "Chicago O'Hare"
  "FCO": "Rome Fiumicino"
  "GIB": "Gibraltar"
  "PEK": "Beijing Capital"
  "RUH": "Riyadh King Khalid"
  "CPH": "Copenhagen"
  "SVQ": "Seville"
  "IST": "Istanbul"
  "TRN": "Turin"
  "AUS": "Austin-Bergstrom"
  "HEL": "Helsinki-Vantaa"
  "VCE": "Venice Marco Polo"
  "LHR - EDI": "London Heathrow to Edinburgh"
  "OUL": "Oulu"
  "OTP": "Bucharest Henri Coandă"
  "MCO": "Orlando"
  "FNC": "Portugal"
  "iAH": "Houston"
  "NCE": "France"
  "YVR-LIS via LHR": "Richmond, Canada"
  "JED": "Jeddah"
  "YUL": "Dorval, Canada"
  "Hannover": "Germany"
  "Kiev": "Ukraine"
  "SSH": "Sharm el-Sheikh, Egypt"
  "Heathrow (London)": "London"
  "Fuereventura": "Spain"
  "lgw": "London"
  "St Kitts": "Saint Kitts and Nevis"
  "DME": "Moscow"
  "Lebanon": "Lebanon"
  "MAN-LHR": "Manchester"
  "Istambul": "Istambul"
  "Verona": "Verona"
  "LHR-BOM": "London"
  "Vancouver Canada": "Vancouver"
  "CAI": "Egypt"
  "Helsinki": "Helsinki"
  "LHR-DEN": "London"
  "ORD-LHR": "Chicago"
  "LHR-GLA": "London"
  "GLA-LHR": "London"
  "SFO/PHX via LHR": "Phoenix"
  "St Lucia via Gatwick": "St Lucia"
  "Luanda via Heathrow": "Luanda"
  "Chicago O'Hare": "Chicago"
  "Rio de Janeiro": "Rio de Janeiro"
  "ATH via LGW": "Athens"
  "Paris via Heathrow": "Paris"
  "Washington Dulles": "Washington"
  "HKG": "Hong Kong"
  "NCE via LHR": "Nice"
  "BCN via LHR": "Barcelona"
  "Bridgetown Grantley Adams": "Bridgetown"
  "Abuja": "Abuja"
  "JNB via LHR": "Johannesburg"
  "Phoenix Sky Harbor": "Phoenix"
  "CDG via LHR": "Paris"
  "Cancún": "Cancun"
  "ZRH via LHR": "Zurich"
  "Dallas/Fort Worth": "Dallas"
  "Prague Václav Havel": "Prague"
  "AMM": "Amman"
  "LAX via LHR": "Los Angeles"
  "LAS via LHR": "Las Vegas"
  "BKK via LHR": "Bangkok"
  "LIM": "Lima"
  "DEN via LHR": "Denver"
  "YUL via LHR": "Montreal"
  "SAN via LHR": "San Diego"
  "CPT via LHR": "Cape Town"
  "YYZ via LHR": "Toronto"
  "ANU": "Antigua"
  "BFS via LHR": "Belfast"
  "MAN via LHR": "Manchester"
  "EZE": "Buenos Aires"
  "DEL via LHR": "Delhi"
  "SVQ via LHR": "Seville"
  "BOM via LHR": "Mumbai"
  "Austin-Bergstrom": "Austin"
  "PVG via LHR": "Shanghai"
  "Seattle-Tacoma": "Seattle"
  "Saint Lucia": "St Lucia"
  "LHR via SIN": "Singapore"
  "BHD": "Belfast"
  "Toronto Pearson": "Toronto"
  "Singapore Changi": "Singapore"
  "BOS via LHR": "Boston"
  "DEL": "Delhi"
  "Kyiv Boryspil": "Kiev"
  "Las Vegas McCarran": "Las Vegas"
  "LHR via LAD & ABV": "Unknown"
  "Baltimore/Washington": "Baltimore"
  "DUR": "Durban"
  "ALC": "Alicante"
  "CLT via LHR": "Charlotte"
  "Boston Logan": "Boston"
  "VLC": "Valencia"
  "SVQ via MAD": "Seville"
  "Bucharest Henri Coandă": "Bucharest"
  "CPT via JNB": "Cape Town"
  "Málaga": "Malaga"
  "EDI via LHR": "Edinburgh"
  "BRU": "Brussels"
  "LHR via BKK": "Bangkok"
  "ATH via LHR": "Athens"
  "France": "France"
  "PRG via LHR": "Prague"
  "NBO via LHR": "Nairobi"
  "FCO via LHR": "Rome"
  "DEN": "Denver"
  "DUB via LHR": "Dublin"
  "LIS via LHR": "Lisbon"
  "Atlanta Hartsfield-Jackson": "Atlanta"
  "DUS via LHR": "Dusseldorf"
  "BGO": "Bergen"
  "ZRH via LCY": "Zurich"
  "SIN via SYD": "Singapore"
  "Amsterdam Schiphol": "Amsterdam"
  "KGS": "Kos"
  "GVA via LHR": "Geneva"
  "BIO": "Bilbao"
  "PER via SIN": "Perth"
  "KRK": "Krakow"
  "SVO": "Moscow"
  "OPO via LGW": "Porto"
  "Shanghai Pudong": "Shanghai"
  "SIN via LHR": "Singapore"
  "Marrakesh Menara": "Marrakesh"
  "BOS, SEA to LHR": "Boston"
  "Paris Charles de Gaulle": "Paris"
  "Dorval, Canada": "Montreal"
  "SXF via LHR": "Berlin"
  "SFO via PHL": "San Francisco"
  "AMS via LHR": "Amsterdam"
  "BWI via LHR": "Baltimore"
  "Nassau Lynden Pindling": "Nassau"
  "CDG via BAH / LHR": "Paris"
  "KUL via LHR": "Kuala Lumpur"
  "FLR": "Florence"
  "SFO via LHR": "San Francisco"
  "MEX via LHR": "Mexico City"
  "BKK via KUL": "Bangkok"
  "EBB via LHR": "Entebbe"
  "EWR": "Newark"
  "MCI via ORD": "Kansas City"
  "FAO": "Faro"
  "San Diego": "San Diego"
  "PFO": "Paphos"
  "STR": "Stuttgart"
  "PHL via LHR": "Philadelphia"
  "INV via LHR": "Inverness"
  "BDA": "Bermuda"
  "IOM": "Isle of Man"
  "GRU via LHR": "Sao Paulo"
  "BOM": "Mumbai"
  "Warsaw Chopin": "Warsaw"
  "Barcelona El Prat": "Barcelona"
  "CTA": "Catania"
  "Portugal": "Portugal"
  "Basel EuroAirport": "Basel"
  "ORD via LHR": "Chicago"
  "JTR": "Santorini"
  "DXB via LHR": "Dubai"
  "HKG via LHR": "Hong Kong"
  "São Paulo Guarulhos": "Sao Paulo"
  "LHR via BAH": "London"
  "Beijing Capital": "Beijing"
  "RTM": "Rotterdam"
  "TXL via LHR": "Berlin"
  "Pisa Galileo Galilei": "Pisa"
  "SEL via LHR": "Seoul"
  "GIG": "Rio de Janeiro"
  "ACC via LHR": "Accra"
  "Helsinki-Vantaa": "Helsinki"
  "LHR via HEL": "London"
  "GIG via LHR": "Rio de Janeiro"
  "TLV via LHR": "Tel Aviv"
  "MIa": "Miami"
  "MLE": "Male"
  "SFO via EDI": "San Francisco"
  "SZG": "Salzburg"
  "LHR via MIA": "London"
  "Jeddah": "Jeddah"
  "Richmond, Canada": "Richmond"
  "NCL via LHR": "Newcastle"
  "MUC via LHR": "Munich"
  "Sharm el-Sheikh, Egypt": "Sharm el-Sheikh"
  "Sydney via LHR": "Sydney"
  "BRU via LHR": "Brussels"
  "BNE via SIN": "Brisbane"
  "Krakow": "Krakow"
  "Germany": "Germany"
  "Dublin via LHR": "Dublin"
  "Luanda": "Luanda"
  "PEK via LHR": "Beijing"
  "AUH via LHR": "Abu Dhabi"
  "Chengdu": "Chengdu"
  "JFK (New York City)": "New York"
  "Saint Kitts and Nevis": "Saint Kitts and Nevis"
  "Haneda": "Tokyo"
  "Cancun via Madrid": "Cancun"
  "SYD via SIN": "Sydney"
  "SVO via LHR": "Moscow"
  "MIA via London": "Miami"
  "alicante": "Alicante"
  "Gatwick via Antigua": "Antigua"
  "JFK via SNN": "New York"
  "Oslo Gardermoen": "Oslo"
  "Granada": "Granada"
  "Paris via LHR": "Paris"
  "Cape Town via LHR": "Cape Town"
  "IAD via LHR": "Washington"
  "Denver via LHR": "Denver"
  "Rome FCO": "Rome"
  "Milan via LHR": "Milan"
  "Manchester via LHR": "Manchester"
  "New York via LHR": "New York"
  "Boston via Heathrow": "Boston"
  "Kuala lumpur": "Kuala Lumpur"
  "Phoenix via LHR": "Phoenix"
  "Nassau": "Nassau"
  "Vancouver via London Heathrow": "Vancouver"
  "DME via LGW / LHR": "Moscow"
  "GLA via LHR": "Glasgow"
  "Orlando via Miami": "Orlando"
  "Lisbon via LHR": "Lisbon"
  "San Fran via London": "San Francisco"
  "Zurich via LHR": "Zurich"
  "Dublin via Heathrow": "Dublin"
  "Entebbe": "Entebbe"
  "Tampa International": "Tampa"
  "Singapire": "Singapore"
  "London LHR": "London"
  "Orlando MCO": "Orlando"
  "JFK via Shannon": "New York"
  "Berlin via London Heathrow": "Berlin"
  "Los Angesles": "Los Angeles"
  "Chicago via LHR": "Chicago"
  "Grand Cayman via Nassau": "Grand Cayman"
  "LUX": "Luxembourg"
  "London to Paris to Rome": "London"
  "Turkey": "Turkey"
